apiVersion: v1
kind: Service
metadata:
  name: freezer-controller
  labels:
    app.kubernetes.io/name: freezer-controller
    app.kubernetes.io/part-of: finguard-deployment-freezer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: freezer-controller
  ports:
    - name: http
      port: 8010
      targetPort: 8010
