apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - payment-api-service.yaml
  - payment-api-deployment.yaml
  - monitoring/payment-api-servicemonitor.yaml
  - monitoring/payment-api-prometheusrule.yaml
