apiVersion: v1
kind: Service
metadata:
  name: payment-api-preview
  labels:
    app.kubernetes.io/name: payment-api-preview
    app.kubernetes.io/part-of: finguard-deployment-freezer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
