apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: finguard
  labels:
    app: payment-api
    component: api
spec:
  type: ClusterIP
  selector:
    app: payment-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
