fullnameOverride: monitoring

crds:
  enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 12h
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

grafana:
  enabled: true
  adminUser: admin
  adminPassword: finguard-admin
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      enabled: true
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 12h
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
